### ISSUE TITLE
multiple-value uuid.NewV4() in single-value context

### ISSUE THREAD

**Issue by stepGitHub** [kuuland/kuu#2]
./acc_routes.go:29:23: multiple-value uuid.NewV4() in single-value context
./sys_routes.go:208:21: multiple-value uuid.NewV4() in single-value context

**Comment by yinfxs** [comment]
Make sure your `github.com/satori/go.uuid` is v1.2.0
https://github.com/satori/go.uuid/blob/v1.2.0/generator.go#L64
